# This is a basic workflow to help you get started with Actions

name: sign-rpms

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: rpmbuild/centos7
      options: --user 1000

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: |
          echo HOME: $HOME
          echo WSPACE: $GITHUB_WORKSPACE
          echo USER: $USER
          echo whoami: `whoami`
          cd
          pwd

      - name: install rpm tools
        run: |
          # apt-get update
          # apt-get install -y rpm
          sudo chown -R builder $HOME
          cat <<EOF > $HOME/.rpmmacros
          %_topdir %(echo $HOME)/rpmbuild
          %_signature gpg
          %_gpg_path %(echo $HOME)/.gnupg
          % _gpg_name RPM Sign
          %__gpg /usr/bin/gpg
          %__gpg_sign_cmd %{__gpg} gpg --force-v3-sigs --batch --pinentry-mode loopback --passphrase-file %(echo $HOME)/passphrase --verbose --no-armor --no-secmem-warning -u "%{_gpg_name}" -sbo %{__signature_filename} --digest-algo sha256 %{__plaintext_filename}'
          EOF

      # from: https://stackoverflow.com/questions/61096521/how-to-use-gpg-key-in-github-actions
      - name: Configure GPG
        run: |
          mkdir -p $HOME/.gnupg/
          ls -lthra $HOME
          # chmod 0600 $HOME/.gnupg
          printf "$GPG_SIGNING_KEY" | base64 --decode > $HOME/.gnupg/private.key
          gpg --batch --import $HOME/.gnupg/private.key
          printf "$GPG_PASSPHRASE" > $HOME/passphrase
          gpg -k
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      # Runs a single command using the runners shell
      - name: Create a test rpm
        run: |
          cat <<EOF > $HOME/test.spec
          Name: Hello
          Version: 1
          Release: 0
          License: BSD
          Summary: A simple test

          %description
          This is a description

          %prep
          rm -rf \$RPM_BUILD_ROOT

          %install
          mkdir -p \$RPM_BUILD_ROOT/pkg
          touch \$RPM_BUILD_ROOT/pkg/hello.txt

          %clean
          rm -rf \$RPM_BUILD_ROOT

          %files
          /pkg/hello.txt
          EOF
          rpmbuild -bb $HOME/test.spec


      # Runs a set of commands using the runners shell
      - name: Sign the rpm
        run: |
          rpmsign --addsign $HOME/rpmbuild/RPMS/x86_64/Hello-1-0.x86_64.rpm
